### ISSUE TITLE
Lock contention when unmarshaling connection query

### ISSUE THREAD

**Issue by faddat** [strangelove-ventures/relayer#21] opened 2021-09-11 00:38 UTC
rly q connection  cosmoshub-4 connection-339

seems to die on me.

**Comment by jackzampolin** [comment] 2021-09-11 13:35
Thanks for the report. Prob something stupid

**Comment by jackzampolin** [comment] 2021-09-11 22:20
so dug into this. We are hanging on the [`MarshalJSON` command in `relayer/contextual.go`](https://github.com/strangelove-ventures/relayer/blob/main/relayer/contextual.go#L25). Looks like some lock contention that is going to be tricky to track down.

**Comment by jackzampolin** [comment] 2021-09-13 23:07
Ok so I found the cause here. https://github.com/strangelove-ventures/relayer/blob/main/relayer/contextual.go#L28 calls https://github.com/strangelove-ventures/relayer/blob/main/relayer/encoding.go#L148. This is leading me rethink and rework the codec code which is good.

**Comment by jackzampolin** [comment] 2021-09-14 00:04
fixed by https://github.com/strangelove-ventures/relayer/pull/34

**Closed by jackzampolin** 2021-09-14 00:04 UTC
Labels: bug
